### ISSUE TITLE
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process:

### ISSUE THREAD

**Issue by mariontan** [smousavi05/EQTransformer#102]
Good Day Thank you for this library it is of great help to us.

I have a question. I keep getting this error when I run the ` predictor` from this library `from EQTransformer.core.predictor import predictor`. I have attached a  screen shot of the error. I was just following the tutoial section from your documentation.

Below are some system details of my machine:
OS: Windows 11
GPU: NVIDIA GeForce RTX 3060 Laptop GPU
![image](https://user-images.githubusercontent.com/1754790/141299191-e353c27e-fb32-46d5-be48-a207e57356b4.png)

**Comment by smousavi05** [comment]
@mariontan currently EqT does not run on Windows. Can you try it on another mac or linux machine?

**Comment by mariontan** [comment]
Thank you very much @smousavi05. Have you tried using this on Windows Subsystem on Linux?

**Comment by smousavi05** [comment]
@mariontan No, I haven't. The core of the code does not have any issue for running on Windows though. The issue is on the auxiliary part of the code creating new folders and arranging the outputs. There is a "/" vs "\" discrepancy between path names in windows and Os. So if you know Python or anyone coding Python on Windows, these issues could be easily solved by following the errors messages and doing some simple modifications to the code. I just do not have any Windows machine to do so or test the code.

**Comment by mariontan** [comment]
Thank you very much @smousavi05.

**Comment by mengzhu555** [comment]
> Hello, have you solved your problem? I still don't understand your conversation above. Can you tell me how to solve the problem of "The process cannot access the file because it is being used by another process"?Thanks so much!

me too

**Comment by smousavi05** [comment]
Another potential solution would be to just use other implementations of
EQTransformer like SeisBench or BlockyEQTransformer.

- Mostafa
